version: 0.0

containers:
  main:
    phases:
      pre_build:
        commands:
          - echo 'Inside CodeBuild Source Directory'
          - ls -altr
      during_build:
        commands:
          - echo 'Compiling the Java Code'
          - mvn assembly:assembly -DdescriptorId=jar-with-dependencies
      post_build:
        commands:
          - echo "Would deploy here"
    artifacts:
      type: zip
      files:
        - 'target/sample-app*'
