version: 0.0

containers:
  main:
    phases:
      install:
        commands:
          - bundle install
      during_build:
        commands:
          - echo "******** Building Jekyll site ********"
          - jekyll build
      post_build:
        commands:
          - echo "******** Uploading to S3 ********"
          - aws s3 sync _site/ s3://jenkinspipelineexample
